apiVersion: v1
kind: PersistentVolume
metadata:
  name: dots-redis-pv
  labels:
    app: redis
    environment: production
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  nfs:
    server: 192.168.1.9
    path: /volume2/k8s/redis
